GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjUwMzM3OTUxLCJleHAiOjE2NTAzMzc5NjZ9.EpC_25wHrY5LH6aH_tbZLiOmofbU6bTNugwdKyhDe14

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjUwMzM4MjY2fQ.MERu4kJUWkGU2JBSOQfiINpFmt9F72FV5tjQqoyKtmg"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjUwMzM4MjY2fQ.MERu4kJUWkGU2JBSOQfiINpFmt9F72FV5tjQqoyKtmg"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Jim"
}